sudo: required
language: node_js
node_js:
  - "8"
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::6}
  - DOCKER_REPO=766261213300.dkr.ecr.eu-west-1.amazonaws.com/face-recognitor
services:
- docker
script:
- npm run lint
- docker build . -t $DOCKER_REPO:$COMMIT --network host