apiVersion: apps/v1
kind: Deployment
metadata:
  name: face-recognitor-deployment
spec:
  selector:
    matchLabels:
      app: face-recognitor-app
  template:
    metadata:
      labels:
        app: face-recognitor-app
    spec:
      containers:
      - name: face-recognitor
        image: 766261213300.dkr.ecr.eu-west-1.amazonaws.com/face-recognitor:latest
        ports:
        - containerPort: 3000
        env:
          - name: NODE_ENV
            value: production

---

apiVersion: v1
kind: Service
metadata:
  name: face-recognitor-service
  labels:
    app: face-recognitor-app
spec:
  ports:
   - port: 3000
  selector:
    app: face-recognitor-app

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: face-recognitor-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: face-recognitor.lab.wunder.dog
    http:
      paths:
      - backend:
          serviceName: face-recognitor-service
          servicePort: 3000

---